#pragma once

#define PJ_HAS_SSL_SOCK 1
#define PJ_SSL_SOCK_IMP PJ_SSL_SOCK_IMP_OPENSSL
#define PJSIP_HAS_TLS_TRANSPORT 1
#define PJMEDIA_HAS_SRTP 1
#define PJMEDIA_SRTP_HAS_DTLS 1
#define PJMEDIA_HAS_OPUS_CODEC 1

#define PJMEDIA_HAS_VIDEO 1
#define PJSUA_HAS_VIDEO 1
#define PJMEDIA_VIDEO_DEV_HAS_SDL 0
#define PJMEDIA_VIDEO_DEV_HAS_FFMPEG 0
#define PJMEDIA_HAS_FFMPEG 0
#define PJMEDIA_HAS_FFMPEG_CODEC 0
#define PJMEDIA_HAS_FFMPEG_VID_CODEC 0
#define PJMEDIA_HAS_OPENH264_CODEC 0
#define PJMEDIA_HAS_VPX_CODEC 0
